notebook/config/routes.rb
Rails.application.routes.draw do
  resources :notes
end

notebook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

notebook/app/models/note.rb
class Note < ApplicationRecord
    
end

notebook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

notebook/app/controllers/notes_controller.rb
class NotesController < ApplicationController
    def index
        @notes = Note.all
        #render :index --> C'est ce qui est fait mais on ne le voit pas
    end

    def new
        @note = Note.new
        #render :new --> C'est ce qui est fait mais on ne le voit pas
    end

    def create #Méthode pour créer
        @note = Note.new(note_params)
        if @note.save
            redirect_to notes_url
        else
            render :new #on réaffiche le formulaire
        end

    end

    def edit #Méthode pour éditer
        @note = Note.find_by(id: params[:id])
        render :new
    end

    def update #Méthode pour mettre à jour
        @note = Note.find_by(id: params[:id])
        if @note.update(note_params)
            redirect_to notes_url
        else
            render :new #on réaffiche le formulaire
        end
    end

    def destroy #Méthode pour supprimer
        note = Note.find_by(id: params[:id])
        note.destroy
        redirect_to notes_url
    end

    def show
        @note = Note.find_by(id: params[:id])
    end

    private
        def note_params
            params.require(:note).permit(:title, :content)
        end
end

notebook/app/helpers/application_helper.rb
module ApplicationHelper
end

notebook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

notebook/app/views/notes/index.html.erb
<p>
    <%= link_to 'Créer une nouvelle note', new_note_url %>
</p>

<ul class='notes'>
<% @notes.each do |note| %>
    <li>
        <%= link_to note.title, note_url(note) %>
        <%= link_to 'Édit', edit_note_url(note) %>
        <%= link_to 'Supprimer', note_url(note), method: :delete %>
    </li>
<% end %>
</ul>

notebook/app/views/notes/new.html.erb
<%= form_for @note do |f| %>
    <p>    
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>
    <p> 
        <%= f.label :content %>
        <%= f.text_area :content %>
    </p>
    <p>
        <%= f.submit 'Sauvegarder' %>
    </p>
<% end %>

notebook/app/views/notes/show.html.erb
<h1><%= @note.title %></h1>

<div class='content'>
    <%= @note.content %>
</div>